[default.extend-words]
Symplify = "Symplify"
Invokable = "Invokable"

# as in 2nd
nd = "nd"

# plurals
Identicals = "Identicals"
Ands = "Ands"
Ors = "Ors"

# native function names
writeable = "writeable"
