<?php

declare(strict_types=1);

namespace Rector\Tests\Restoration\Rector\ClassLike\UpdateFileNameByClassNameFileSystemRector\FixtureUsingMultipleFilesChangedTrait;

final class SkipDifferentClassName
{

}
-----
-----
SkipDifferentClassName.php
-----
-----
<?php

declare(strict_types=1);

namespace Rector\Tests\Restoration\Rector\ClassLike\UpdateFileNameByClassNameFileSystemRector\FixtureUsingMultipleFilesChangedTrait;

final class SkipDifferentClassName
{

}
