<?php

namespace Rector\Tests\Php80\Rector\ClassMethod\AddParamBasedOnParentClassMethodRector\Fixture;

use Rector\Tests\Php80\Rector\ClassMethod\AddParamBasedOnParentClassMethodRector\Source\InterfaceWithParam;

class ImplementsInterfaceFromSource implements InterfaceWithParam {
    public function execute()
    {
    }
}

?>
-----
<?php

namespace Rector\Tests\Php80\Rector\ClassMethod\AddParamBasedOnParentClassMethodRector\Fixture;

use Rector\Tests\Php80\Rector\ClassMethod\AddParamBasedOnParentClassMethodRector\Source\InterfaceWithParam;

class ImplementsInterfaceFromSource implements InterfaceWithParam {
    public function execute($foo)
    {
    }
}

?>
