# builds the content of https://github.com/rectorphp/rector-prefixed
# inspiration from https://github.com/phpstan/phpstan-src/blob/master/.github/workflows/phar.yml
name: Packages Tests

on:
    pull_request: null
    push:
        branches:
            - main

env:
    # see https://github.com/composer/composer/issues/9368#issuecomment-718112361
    COMPOSER_ROOT_VERSION: "dev-main"

jobs:
    packages_tests:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                package_name:
                    - rectorphp/rector-nette
<<<<<<< HEAD
                    - rectorphp/rector-nette-to-symfony
=======
<<<<<<< HEAD
=======
                    - rectorphp/rector-nette-to-symfony
>>>>>>> 9c8ff2cde ([CI] test typo3 package too)
>>>>>>> 384b11677 ([TASK] Build rector/rector with typo3-rector included)
                    - rectorphp/rector-symfony
                    - rectorphp/rector-laravel
                    - rectorphp/rector-phpunit
                    - rectorphp/rector-cakephp
                    - rectorphp/rector-doctrine
<<<<<<< HEAD
<<<<<<< HEAD
=======
                    - ssch/typo3-rector
>>>>>>> 9c8ff2cde ([CI] test typo3 package too)
=======
>>>>>>> 153da8c2a ([TASK] Do not prefix Ssch namespace)

        steps:
            -
                uses: "actions/checkout@v2"
                with:
                    repository: ${{ matrix.package_name }}

            -
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.0
                    coverage: none

            -   run: composer install --ansi

            -   run: vendor/bin/phpunit
